[[pages]]
path = "main.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "scripts/hosted_fms.py"
name = "Bedrock FMs"
icon = ":clipboard:"

[[pages]]
path = "scripts/qa_fm.py"
name = "QA - Single FM ğŸ“™"
icon = ":question:"

[[pages]]
path = "scripts/qa_fm_comparison.py"
name = "QA - FM Comparison ğŸ“š"
icon = ":question:"

[[pages]]
path = "scripts/text_search.py"
name = "Text Search"
icon = ":mag_right:"

[[pages]]
path = "scripts/code_translation.py"
name = "Code Translation"
icon = ":abacus:"

[[pages]]
path = "scripts/rag_documents.py"
name = "RAG - Document(s)"
icon = ":file_folder:"

[[pages]]
path = "scripts/rag_bedrock_kb.py"
name = "RAG - Bedrock KB"
icon = ":bucket:"

[[pages]]
path = "scripts/solutions_overview.py"
name = "Solutions Overview"
icon = ":triangular_ruler:"